import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import Contact from './Contact';
import Skill from './Skill';
import About from './About';
import Counter from './Counter';
import Navbar from '../components/Navbar';
import COunter from '../components/Counter';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar />
      <p>hellow this is main page</p>
      <Link href="/About">About </Link>
      <Link href="/Contact">Contact </Link>
      <Link href="/Skill">Skill </Link>

      <Counter />
      <div className="card">
        <div className="card-body text-center">
          
        </div>
      </div> */}
      <COunter />
    </div>
  )
}
